apiVersion: v1
kind: Pod
metadata:
  name: meu-pod-reader
  namespace: default
  labels:
    app: meu-pod-reader
spec:
  serviceAccountName: pod-reader
  containers:
  - name: leitor-de-pod
    image: alpine:latest
    command: ["sleep", "infinity"]